// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL2vELltApewuFRZR84q7Muwb5a_Cx5LM',
    appId: '1:393125280634:web:aad2a360c1048acd48b4c3',
    messagingSenderId: '393125280634',
    projectId: 'chat-app-6a98e',
    authDomain: 'chat-app-6a98e.firebaseapp.com',
    storageBucket: 'chat-app-6a98e.appspot.com',
    measurementId: 'G-3DJ1SYQ1GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH64wgPsHox_TicFquulgUirFbMdvRBws',
    appId: '1:393125280634:android:2bfd75a422ce604c48b4c3',
    messagingSenderId: '393125280634',
    projectId: 'chat-app-6a98e',
    storageBucket: 'chat-app-6a98e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfMY75_KHXadibADUSwDI45POPUZHBCaA',
    appId: '1:393125280634:ios:5727424f789e3dbd48b4c3',
    messagingSenderId: '393125280634',
    projectId: 'chat-app-6a98e',
    storageBucket: 'chat-app-6a98e.appspot.com',
    iosClientId: '393125280634-sfj3vinrvu1vudigo3n07ds7c3iehlgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.newChatApp',
  );
}
